### ISSUE TITLE
Using GEM-FISH with custom genome data

### ISSUE THREAD

**Issue by El-Castor** [ahmedabbas81/GEM-FISH#2]
Hi, 

thanks for this work, it's very nice. I was wondering if I can used your software with my own HiC and FISH data in a genome that is not human genome or you have hard-coded your scripts related to the human genome?

Thanks in advances

**Comment by ahmedabbas81** [comment]
Hello,
I am sorry for the very late reply

I just saw the issue. I am very sorry.
It should be possible to use it and if you face trouble, please let me know. I will be happy to help you

Thanks
